subspace_consistency:
    num_bootstraps: 100
    smoothing_kernel_std: 0.05
    analysis_bin_size: 0.05
    subselect_co_horiz_trials: False
co_dpca:
    co_rel_start_time: -0.4
    co_rel_end_time: 0.5
    cst_rel_start_time: -0.4
    cst_rel_end_time: 5
    smoothing_kernel_std: 0.05
    softnorm_rates: False
dimensionality:
    smoothing_kernel_std: 0.050
    analysis_bin_size: 0.50
    softnorm_rates: False
    n_folds: 5
    n_repeats: 1